FROM jboss/wildfly:${version.wildfly}

MAINTAINER Francis Pouatcha <fpo@adorsys.com>

EXPOSE 8080 8787 9990 9999 8443

RUN rm -rf $JBOSS_CONFIG_DIR/standalone_xml_history

WORKDIR $JBOSS_HOME

COPY adcom.deploy.tar.gz /
RUN cd $JBOSS_HOME && tar xf /adcom.deploy.tar.gz 

COPY launch-idp-server /

CMD ["bash", "/launch-idp-server"]



