package org.adorsys.adcore.enums;

public enum CoreHistoryTypeEnum {
	INFO, INITIATED, APPROVAL_REQUESTED, APPROVED, 
	FAILED_APPROVAL, DENIED_APPROVAL, FROZEN_APPROVING, 
	FROZEN_ABANDONED, FROZEN_TERMINATED, MODIFIED, CANCELED, 
	FAILED_CANCELATION, COMMITTED, FAILED_COMMITMENT, 
	CLOSED, FAILED_CLOSING, POSTED, 
	REVERSED, FAILED_REVERSE, RECALL, 
	FAILED_RECALL, CLOSING, ITEM_MODIFIED, 
	SUSPENDED, RESUMED, DELIVERED, 
	RETURNED, DELETED, ITEM_UPDATED, ITEM_CREATED, ITEM_DELETED, POSTING, ARCHIVED
}